---
abstract: 'a profiler printing at once instead of recording queries.'
author:
  - 'Makamaka Hannyaharamitu, <makamaka[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Skinny-Profiler-ProfileLogger
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Skinny: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/makamaka/p5-dbix-skinny-profiler-profilelogger
version: 0.05
